// 100+ sarcastic college student jokes
export const JOKES: readonly string[] = [
  "Attendance: 74%. Professor: 'You sure you go here?'",
  "Studied for 3 hours. Forgot in 3 minutes. Beautiful symmetry.",
  "My sleep schedule is on a gap year.",
  "Group project = solo project with extra steps.",
  "I don't have anxiety. My CGPA does.",
  "8 AM class? In this economy?",
  "I'm not procrastinating. I'm marinating ideas.",
  "My brain has 47 tabs open and one is playing music. Can't find which.",
  "I peaked in syllabus week.",
  "My attendance is more inconsistent than the canteen WiFi.",
  "Maggi is a personality at this point.",
  "Backbenchers don't sit at the back. The back forms around them.",
  "Mid-sem syllabus: 4 chapters. Studied: 0.5. Vibes: rich.",
  "My notes look like ancient scripture decoded by raccoons.",
  "I attend lectures the way ghosts attend their own funerals.",
  "The library has seen me cry in 3 languages.",
  "Caffeine is my emotional support beverage.",
  "I don't need therapy. I need an extension.",
  "Slept at 4. Class at 8. Death at 9.",
  "My GPA is in its lore arc.",
  "Bro just send the PYQs. I'll figure out the rest.",
  "I'm not cramming. I'm speedrunning education.",
  "Class is just expensive napping with extra steps.",
  "Don't judge me. The deadline gave me trauma.",
  "I'm built for chaos and 11:59 PM submissions.",
  "Hostel mess? More like mess hostel.",
  "Senior advice: study, sleep, social. Pick one.",
  "I've been 'about to start studying' since August.",
  "The professor said 'this will be in the exam'. I blacked out.",
  "My attention span has the half-life of a TikTok.",
  "Group chat: 80% memes, 20% panic.",
  "I don't bunk. I conserve cognitive bandwidth.",
  "Internal marks are a performance art.",
  "I applied for an extension. The extension applied for therapy.",
  "Professor uploaded slides at 11:58. Exam at 12. Make it make sense.",
  "Crying in the canteen is a college sport.",
  "I'm not poor. I'm 'engineering student' financially.",
  "Showered. Ate. Survived. Productivity unlocked.",
  "Notes? I have one (1) word and a doodle of a duck.",
  "Mentally I'm at the post-grad. Academically I'm at the front-page.",
  "My 'started preparing' and 'gave the exam' are 6 hours apart.",
  "Bunk = self-care.",
  "Lab record is just creative fiction.",
  "Studying with friends = expensive group chat.",
  "I love deadlines. I love the whooshing sound they make as they fly by.",
  "If sleep deprivation paid GPA points, I'd graduate summa cum laude.",
  "Attended 1 class. Felt productive for 3 days.",
  "PYQs are just exam spoilers and we love that.",
  "I haven't been on time since orientation.",
  "My brain runs on memes and Maggi.",
  "Classroom Wi-Fi: trust issues activated.",
  "I don't fear exams. I fear the silence after submitting blank papers.",
  "Read the syllabus twice. Understood: no.",
  "My time management has a manager.",
  "Sleep is a concept. Like fairness.",
  "I'm one extension away from peace.",
  "If overthinking burned calories, I'd be shredded.",
  "Library: silent. Brain: not so much.",
  "I treat sleep like cash. Save it. Spend it. Regret it.",
  "Internal exams hit different when you forget you have them.",
  "Slept through the alarm. The alarm slept through me back.",
  "Attendance is a gentle suggestion.",
  "Bunk. Repent. Repeat.",
  "My GPA is climbing. So is my anxiety. Different ladders.",
  "Professor: 'Any questions?' Class: collective dissociation.",
  "I'm functioning at 12% and that's still 12 percent more than yesterday.",
  "Friend: 'How was the test?' Me: 'It happened.'",
  "Wrote one line. Called it the introduction. Slept.",
  "I don't choose chaos. Chaos has a subscription to me.",
  "My sleep cycle has a sleep cycle.",
  "The library closes at 10. My will to live closes at 7.",
  "Internal marks: I asked nicely. They said no.",
  "I write my own notes the night before, in another language somehow.",
  "If revising counted as cardio, I'd be ripped.",
  "It's not procrastination if you call it 'strategy.'",
  "I pulled an all-nighter to study. Studied: 14 minutes.",
  "Survival skill: nodding seriously while completely lost.",
  "My handwriting is bilingual: legible, and not.",
  "Day before exam = lifetime of regret in one night.",
  "We don't 'graduate.' We escape.",
  "Mid-sems are personality reveals.",
  "I asked for a nap. Universe gave me a class.",
  "Attendance bot? More like attendance god.",
  "Slept like a baby. Cried every two hours.",
  "If blinking burned syllabus, I'd be done.",
  "Hostel ceiling: my therapist.",
  "Friend: 'You okay?' Me: 'I have a viva tomorrow.' Friend: 'Oh.'",
  "I made a study plan. The plan made fun of me.",
  "PowerPoint slides: 47. Brain capacity: 3.",
  "Professor's pace: light speed. Mine: light flicker.",
  "The grades are made up and the credits don't matter (until they do).",
  "Engineering: the art of solving problems you didn't know existed in ways you don't understand.",
  "I'm not avoiding studying. I'm waiting for divine intervention.",
  "Notes are forever. Memory is a suggestion.",
  "Whoever invented 8 AM classes owes me reparations.",
  "I'm fluent in 'pretending I read the chapter.'",
  "My attendance has main character energy: dramatic and rare.",
  "Professor: 'It's a conceptual question.' Class: dies.",
  "Coffee is the only adult I trust.",
  "Student loans? More like student groans.",
  "I treat assignments like horoscopes — vague, late, and somehow accurate.",
  "Bro just gave me his notes. Saved my degree.",
  "Don't tell mom my attendance.",
  "The exam was tough. So was getting out of bed.",
];

export function jokeOfDay(date = new Date()): string {
  const i = (date.getFullYear() * 421 + (date.getMonth() + 1) * 17 + date.getDate() * 7) % JOKES.length;
  return JOKES[i];
}
