// 100+ motivational quotes — short, punchy, student-flavored
export const QUOTES: readonly string[] = [
  "You don't have to be great to start, but you have to start to be great.",
  "The expert in anything was once a beginner who refused to quit.",
  "Discipline is choosing what you want most over what you want now.",
  "Future you is watching. Don't disappoint them.",
  "Small steps every day beat one giant leap once a year.",
  "The grind is silent. The reward is loud.",
  "You're not behind. You're on your timeline.",
  "Hard now, easy later. Easy now, hard later.",
  "The 6 a.m. version of you would high-five present you.",
  "Effort is the only currency that never depreciates.",
  "Sleep is for after the deadline.",
  "Momentum is built in 25-minute blocks.",
  "Your future self is begging you to start.",
  "The library doesn't care about your mood.",
  "Show up tired. Show up anyway.",
  "Comparison is the thief of GPA.",
  "Talent gets you noticed. Consistency gets you remembered.",
  "Progress over perfection. Always.",
  "You can rest when the semester ends.",
  "One more rep. One more page. One more line.",
  "Mood follows action — not the other way around.",
  "The pain of discipline weighs ounces. Regret weighs tons.",
  "Don't break the chain.",
  "Be the student your mom thinks you are.",
  "Hard work beats talent when talent doesn't show up.",
  "Your only competition is yesterday's you.",
  "Read it once more. It clicks the third time.",
  "If it scares you, it matters.",
  "Done is better than perfect.",
  "Trust the boring days.",
  "The best time to start was yesterday. The second best is now.",
  "Iterate, don't ideate.",
  "Stop scrolling. Start solving.",
  "You vs. you. Always.",
  "Class skipped is interest accruing.",
  "Cgpa heals. Hustle heals harder.",
  "Discipline is freedom in disguise.",
  "Be addicted to your future.",
  "Energy follows attention.",
  "Boring routines build glamorous lives.",
  "Stay broke until you're built.",
  "The dream doesn't work unless you do.",
  "You're closer than you think.",
  "Make peace with the process.",
  "Your phone won't write the assignment.",
  "Output > intent.",
  "Show up on the bad days. Especially then.",
  "Stress is just unprocessed potential.",
  "If not now, when? If not you, who?",
  "Win the morning, win the day.",
  "Hydrate. Recalibrate. Dominate.",
  "Practice till easy. Then practice some more.",
  "You don't need motivation. You need a deadline.",
  "Be patient with results, impatient with effort.",
  "Read the question twice. Solve it once.",
  "Wake up. Beat yesterday. Sleep. Repeat.",
  "Excuses don't build resumes.",
  "Pressure makes diamonds. And toppers.",
  "Don't aim. Calibrate. Then fire.",
  "There's no traffic on the extra mile.",
  "Make the boring choice. Boring scales.",
  "Quiet ego, loud results.",
  "Notes today, freedom tomorrow.",
  "Even slow progress is lapping the couch.",
  "Tough days don't last. Tough students do.",
  "Be the algorithm of your own success.",
  "Your goals don't care about your mood swings.",
  "Productivity is just rest planned well.",
  "Today is a draft of tomorrow.",
  "Stop waiting for the perfect plan.",
  "Be obsessed or be average.",
  "Do it scared.",
  "Confidence is a side effect of preparation.",
  "Reps over rage.",
  "Burn the boats. Take the exam.",
  "If you got time to scroll, you got time to study.",
  "There's a version of you that already made it. Become them.",
  "Don't dim your light to fit a curve.",
  "Romance the routine.",
  "Outwork your doubt.",
  "Be unbothered. Be unbothered. Be unbothered.",
  "Learning is the only flex.",
  "Make the syllabus your enemy. Then your friend.",
  "Energy is finite. Spend it on what compounds.",
  "Underestimated is the best place to be.",
  "The grind doesn't lie.",
  "Stop performing. Start producing.",
  "Master the basics. Then break them.",
  "Self-respect is a 7 a.m. alarm honored.",
  "Lock in.",
  "You're built different. Act like it.",
  "The work is the way.",
  "Don't trade long-term peace for short-term comfort.",
  "You owe yourself the effort.",
  "Become the person your goals require.",
  "Your potential is patient. Are you?",
  "Bet on yourself. The odds are great.",
  "Win quietly. Brag with your CGPA.",
  "There's beauty in repetition.",
  "Tomorrow is a thief. Pay yourself today.",
  "Pain is the price. Pay it.",
  "You are the project.",
  "Stay the course. The course is staying.",
  "Be 1% better. The interest compounds.",
  "Discomfort is data.",
  "Build daily. Brag never.",
];

export function quoteOfDay(date = new Date()): string {
  const i = (date.getFullYear() * 372 + (date.getMonth() + 1) * 31 + date.getDate()) % QUOTES.length;
  return QUOTES[i];
}
